Repository haddocking/pdb-tools, pull requests merged in 2020-08, with the labels that each got.

#69 pdb_reres was ignoring MODEL lines
  pdbtools/pdb_reres.py
  tests/data/ensemble_more_OK.pdb
  tests/test_pdb_reres.py
Labels: bug

#74 Ignores CONECT lines in pdb_tidy
  pdbtools/pdb_tidy.py
  tests/test_pdb_tidy.py
Labels: enhancement

#76 Deleted unreachable/duplicated return statements
  pdbtools/pdb_delresname.py
  pdbtools/pdb_selatom.py
  pdbtools/pdb_selresname.py
Labels: bug

#75 [FEATURE] Added new tool to assign unique names to HETATM atoms + tests
  pdbtools/pdb_uniqname.py
  tests/data/hetatm.pdb
  tests/data/hetatm_bad.pdb
  tests/test_pdb_uniqname.py
Labels: enhancement

#80 Added -strict option to pdb_tidy to avoid adding intra-chain TERs
  pdbtools/pdb_tidy.py
  tests/test_pdb_tidy.py
Labels: enhancement

#81 Adds tool pdb_chainbows to sequentially assign chain identifiers
  pdbtools/pdb_chainbows.py
  tests/test_pdb_chainbows.py
Labels: Tool Request, enhancement
